require 'rspec/core/rake_task'
require 'rubocop/rake_task'

RSpec::Core::RakeTask.new('spec') do |t|
  t.rspec_opts = '--color --format documentation --require helpers/spec_helper'
end

RuboCop::RakeTask.new
